import { UnitPrice, Unit } from './price-list.service';

export const additionalWorkPrice: UnitPrice[] = [
  { name: 'Ремонт ПВХ потолка', unit: Unit.LinearMeter, price: [5000] },
  { name: 'Слив воды с натяжного потолка', unit: Unit.LinearMeter, price: [700] },
  { name: 'Профиль алюминиевый + штапик + плинтус + монтаж', unit: Unit.LinearMeter, price: [250] },
  { name: 'Дополнительный угол (более 4-х в помещении)', unit: Unit.LinearMeter, price: [200] },
  { name: 'Обход трубы с окантовкой', unit: Unit.LinearMeter, price: [200, 300] },
  { name: 'Крепление люстры универсальное', unit: Unit.Things, price: [400] },
  { name: 'Снятие / Монтаж люстры', unit: Unit.Things, price: [200, 1000] },
  { name: 'Стойка и отверстие для точечного светильника R-50, R-63', unit: Unit.Things, price: [400] },
  { name: 'Опускание светильников от потолка на 20-40 см', unit: Unit.Things, price: [150] },
  { name: 'Опускание светильников от потолка на 40 см и более', unit: Unit.Things, price: [400] },
  { name: 'Светильник с установкой', unit: Unit.Things, price: 'договорная' },
  { name: 'Перфоратор с пылесосом', unit: Unit.LinearMeter, price: [50] },
  { name: 'Монтаж электропроводки', unit: Unit.Point, price: [50] },
  { name: 'Установка трансформатора для питания светильников', unit: Unit.Things, price: [200] },
  { name: 'Стойка и отверстие для элемента пожарной сигнализации', unit: Unit.Things, price: [400] },
  { name: 'Установка бруса', unit: Unit.Point, price: 100 },
  { name: 'Обход кондиционера', unit: Unit.Things, price: [500, 1000] },
  { name: 'Криволинейный участок', unit: Unit.LinearMeter, price: [500] },
  { name: 'Укрепление профиля косыми распорами	', unit: Unit.LinearMeter, price: [150, 200] },
  { name: 'Установка разделителя', unit: Unit.LinearMeter, price: [300] },
  { name: 'Монтаж потолочного карниза', unit: Unit.LinearMeter, price: [500] },
  {
    name: 'Монтаж на сложную поверхность (плитка, керамогранит, ГКЛ и др.)',
    unit: Unit.LinearMeter,
    price: [150, 500],
  },
  { name: 'Демонтаж полотна', unit: Unit.LinearMeter, price: 'договорная' },
  { name: 'Монтаж теневого профиля Еврокрааб (работа + материал)', unit: Unit.LinearMeter, price: 1100 },
  { name: 'Бесщелевая система крепления', unit: Unit.LinearMeter, price: 1900 },
  { name: 'Теневой для ткани EuroSloTT', unit: Unit.LinearMeter, price: 1800 },
  { name: 'Обход внешних углов на теневой системе крепления', unit: Unit.Things, price: 1000 },
  { name: 'Обход внутренних углов на теневой системе крепления', unit: Unit.Things, price: 500 },

  { name: 'Закладные под светильники(круглые, стандарт) электроразводка', unit: Unit.LinearMeter, price: 500 },
  { name: 'Закладные под светильники (квадратные) электроразводка', unit: Unit.LinearMeter, price: 1000 },
  { name: 'Закладные под светильники (квадратные) электроразводка', unit: Unit.LinearMeter, price: 1500 },

  { name: 'Закладная под люстру', unit: Unit.Things, price: 600 },
  { name: 'Световая линия Flexy 5см.', unit: Unit.LinearMeter, price: 3800 },
  { name: 'Световая линия Flexy 3см.', unit: Unit.LinearMeter, price: 4300 },
  { name: 'Подсветка карниза', unit: Unit.LinearMeter, price: 1000 },
  { name: 'Ниша с перегибом полотна', unit: Unit.LinearMeter, price: 1200 },
  { name: 'Монтаж парящего профиля с подсветкой стены ( работа, материал)', unit: Unit.LinearMeter, price: 1800 },
  { name: 'Парящий профиль для тканевых потолков( работа, материал)', unit: Unit.LinearMeter, price: 2000 },
  { name: 'Монтаж контурного профиля с подсветкой стены', unit: Unit.LinearMeter, price: 1100 },
  { name: 'Монтаж трубоотвода', unit: Unit.LinearMeter, price: 600 },
  { name: 'Деревянный брус с креплением', unit: Unit.LinearMeter, price: 600 },
  { name: 'Отбойник', unit: Unit.LinearMeter, price: 1000 },
  { name: 'Монтаж по керамограниту', unit: Unit.LinearMeter, price: 600 },
  { name: 'Обход кондиционера', unit: Unit.LinearMeter, price: 1500 },
] as const;
